---
name: NetSDS-Util
version: 1.02
author:
  - 'Net.Style Development Team <info@netstyle.com.ua>'
abstract: Utility Perl5 modules for NetSDS VAS development framework
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
requires:
  NetSDS: 1.02
  perl: 5.008
  version: 0
build_requires:
  Module::Build: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  NetSDS::Util::Convert:
    file: lib/NetSDS/Util/Convert.pm
    version: 1.00
  NetSDS::Util::String:
    file: lib/NetSDS/Util/String.pm
    version: 0.01
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
